### ISSUE TITLE
Add support for creating a pull request.

### ISSUE THREAD

**Issue by jackton1** [tj-actions/bumpversion#8]
* bumpversion:

### Description

Update to create a Pull request.

```yaml
    steps:
    - uses: actions/checkout@v2
      
    - name: Run isort
      uses: olance/isort-action@v1.0.0
      with:
        args: .
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
